name: Send Email Report
on:
  workflow_call:
  workflow_dispatch:

env:
  EMAIL_USERNAME: ${{secrets.EMAIL_USERNAME}}
  EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
  EMAIL_DEV: ${{ secrets.EMAIL_DEV }}

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Download Financial Report
        uses: actions/download-artifact@v4
        with:
          name: financial-discount
          # This ensures the file is placed where the script expects it
          path: spreadsheet/financial_discount.xlsx

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Send email
        run: python sender.py
