name: Send Email Report
on:
  workflow_call:
  workflow_dispatch:

#env:
#  EMAIL_USERNAME: ${{secrets.EMAIL_USERNAME}}
#  EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
#  EMAIL_DEV: ${{ secrets.EMAIL_DEV }}

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Send email
        id: send_email
        run: python sender.py

      - name: Debug email
        run: |
          echo "Sending from: Amine Upwork <${{ secrets.EMAIL_USERNAME }}>"


      - name: Send mail with attachment
        uses: dawidd6/action-send-mail@v15
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ steps.send_email.outputs.email_title }}
          to: ${{ secrets.EMAIL_DEV }}
          from: ${{ secrets.EMAIL_USERNAME }}>
          body: ""
          attachments: spreadsheet/financial_discount.xlsx
